SELECT 
    cad.id AS id,
    cad.pro_origem_id AS cad_pro_origem_id,
    cad.tipo AS cad_tipo,
    cad.active AS cad_active,
    cad.sigla_pronome_tratamento AS cad_sigla_pronome_tratamento,
    cad.nome AS cad_nome,
    cad.cnpj_cpf AS cad_cnpj_cpf,
    cad.remember_token AS cad_remember_token,
    cad.created_by AS cad_created_by,
    cad.created_by_name AS cad_created_by_name,
    cad.updated_by AS cad_updated_by,
    cad.updated_by_name AS cad_updated_by_name,
    cad.created_at AS created_at,
    cad.updated_at AS updated_at,
    cad.deleted_at AS deleted_at,
    
    end.id AS end_id,
    end.cadastro_id AS end_cadastro_id,
    end.favorito AS end_favorito,
    end.cep AS end_cep,
    end.tipo_logradouro AS end_tipo_logradouro,
    end.logradouro AS end_logradouro,
    end.numero AS end_numero,
    end.complemento AS end_complemento,
    end.bairro AS end_bairro,
    end.cidade AS end_cidade,
    end.estado AS end_estado,
    end.pais AS end_pais,
    end.ponto_referencia AS end_ponto_referencia,
    end.latitude AS end_latitude,
    end.longitude AS end_longitude,
    end.regiao AS end_regiao,
    end.tipo_imovel AS end_tipo_imovel,
    end.informacao_acesso AS end_informacao_acesso,
    end.area_risco AS end_area_risco,
    end.created_by AS end_created_by,
    end.created_by_name AS end_created_by_name,
    end.updated_by AS end_updated_by,
    end.updated_by_name AS end_updated_by_name,
    end.created_at AS end_created_at,
    end.updated_at AS end_updated_at,
    end.deleted_at AS end_deleted_at
FROM 
    pro_cadastro cad
LEFT JOIN 
    pro_cad_endereco end ON cad.id = end.cadastro_id;