select `circ`.`id` AS `id`,
    `circ`.`cadastro_cliente_id` AS `circ_cadastro_cliente_id`,
    `circ`.`operacao` AS `circ_operacao`,
    `circ`.`velocidade_id` AS `circ_velocidade_id`,
    `circ`.`endereco_id` AS `circ_endereco_id`,
    `circ`.`sigla` AS `circ_sigla`,
    `circ`.`status` AS `circ_status`,
    `circ`.`active` AS `circ_active`,
    `circ`.`nome` AS `circ_nome`,
    `circ`.`data_ativacao` AS `circ_data_ativacao`,
    `circ`.`data_cancelamento` AS `circ_data_cancelamento`,
    `circ`.`SEI` AS `circ_SEI`,
    `circ`.`created_by` AS `circ_created_by`,
    `circ`.`created_by_name` AS `circ_created_by_name`,
    `circ`.`updated_by` AS `circ_updated_by`,
    `circ`.`updated_by_name` AS `circ_updated_by_name`,
    `circ`.`created_at` AS `created_at`,
    `circ`.`updated_at` AS `updated_at`,
    `circ`.`deleted_at` AS `deleted_at`,
    `vel`.`id` AS `vel_id`,
    `vel`.`cadastro_prestadora_id` AS `vel_cadastro_prestadora_id`,
    `vel`.`tipo_servico` AS `vel_tipo_servico`,
    `vel`.`velocidade` AS `vel_velocidade`,
    `vel`.`link` AS `vel_link`,
    `vel`.`estoque` AS `vel_estoque`,
    `vel`.`custo_unitario` AS `vel_custo_unitario`,
    `vel`.`created_by` AS `vel_created_by`,
    `vel`.`created_by_name` AS `vel_created_by_name`,
    `vel`.`updated_by` AS `vel_updated_by`,
    `vel`.`updated_by_name` AS `vel_updated_by_name`,
    `vel`.`created_at` AS `vel_created_at`,
    `vel`.`updated_at` AS `vel_updated_at`,
    `vel`.`deleted_at` AS `vel_deleted_at`
from (
        `pro_circuito` `circ`
        left join `pro_velocidade` `vel` on((`circ`.`velocidade_id` = `vel`.`id`))
    )